#!/usr/bin/env python
# -*- Mode: python; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright (C) 2016 Aleksander Morgado <aleksander@aleksander.es>
#

import sys

import gi
gi.require_version('ModemManager', '1.0')
from gi.repository import Gio, GLib, GObject, ModemManager


if __name__ == "__main__":

    # Process input arguments
    if len(sys.argv) != 3:
        sys.stderr.write('error: wrong number of arguments\n')
        sys.stdout.write('usage: sms-python <NUMBER> <TEXT>\n')
        sys.exit(1)

    # Prepare SMS properties
    sms_properties = ModemManager.SmsProperties.new ()
    sms_properties.set_number(sys.argv[1])
    sms_properties.set_text(sys.argv[2])

    # Connection to ModemManager
    connection = Gio.bus_get_sync (Gio.BusType.SYSTEM, None)
    manager = ModemManager.Manager.new_sync (connection, Gio.DBusObjectManagerClientFlags.DO_NOT_AUTO_START, None)
    if manager.get_name_owner() is None:
        sys.stderr.write('ModemManager not found in bus')
        sys.exit(2)

    # Iterate modems and send SMS with each
    for obj in manager.get_objects():
        messaging = obj.get_modem_messaging()
        sms = messaging.create_sync(sms_properties)
        sms.send_sync()
        print('%s: sms sent' % messaging.get_object_path())
