.\" ModemManager(8) manual page
.\"
.\" Copyright (C) 2011 Aleksander Morgado
.\"
.TH MODEMMANAGER "8" "31 October 2011"
.SH NAME
ModemManager \- modem management daemon
.SH SYNOPSIS
.B ModemManager [\-\-version] | [\-\-help]
.PP
.B ModemManager [\-\-debug] [\-\-log\-level=<level>] [\-\-log\-file=<filename>] [\-\-timestamps] [\-\-relative\-timestamps]
.SH DESCRIPTION
The ModemManager daemon provides a unified high level API
for communicating with (mobile broadband) modems. While the basic commands are
standardized, the more advanced operations (like signal quality monitoring
while connected) varies a lot.
.TP
ModemManager is a system daemon and is not meant to be used directly from the
command line.
.SH OPTIONS
The following options are supported:
.TP
.I "\-\-version"
Print the ModemManager software version and exit.
.TP
.I "\-\-help"
Print ModemManager's available options and exit.
.TP
.I "\-\-debug"
Runs ModemManager with "DEBUG" log level and without daemonizing. This is useful
for debugging, as it directs log output to the controlling terminal in addition to
syslog.
.TP
.I "\-\-log\-level=<level>"
Sets how much information ModemManager sends to the log destination (usually
syslog's "daemon" facility). By default, only informational, warning, and error
messages are logged. Given level must be one of "ERR", "WARN", "INFO" or "DEBUG".
.TP
.I "\-\-log\-file=<filename>"
Specify location of the file where ModemManager will dump its log messages,
instead of syslog.
.TP
.I "\-\-timestamps"
Include absolute timestamps in the log output.
.TP
.I "\-\-relative-timestamps"
Include timestamps, relative to the start time of the daemon, in the log output.
.TP

.SH SEE ALSO
.BR NetworkManager (8).
